"""Add score column to AIMemory

Revision ID: d15ca02ea8c8
Revises: ffc8d35ad4f1
Create Date: 2025-06-24 14:13:41.106249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15ca02ea8c8'
down_revision = 'ffc8d35ad4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_memory', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
