from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
import os
import datetime
import re


def sanitize_filename(name: str) -> str:
    """Премахва неподходящи символи за файлово име"""
    return re.sub(r'[^\w\-_.]', '_', name)



def export_to_pdf(log_text: str, gpt_response: str, filename: str):
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    y = height - 40

    # Заглавие
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, y, "CyberEdu AI SOC Report")
    y -= 30

    # 🖼 Добави лого (по избор — ако имаш .png файл)
    # try:
    #     c.drawImage("static/assets/logo.png", width - 120, height - 70, width=70, preserveAspectRatio=True)
    # except:
    #     pass  # ако няма логото, не крашваме

    # Log Section
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "Log:")
    y -= 20

    c.setFont("Courier", 9)
    for line in log_text.splitlines():
        c.drawString(40, y, line)
        y -= 12
        if y < 70:
            draw_footer(c, width)
            c.showPage()
            y = height - 40

    # AI Analysis
    y -= 10
    c.setFont("Helvetica-Bold", 11)
    c.drawString(40, y, "GPT Analysis:")
    y -= 20

    c.setFont("Helvetica", 10)
    for line in gpt_response.splitlines():
        c.drawString(40, y, line)
        y -= 13
        if y < 70:
            draw_footer(c, width)
            c.showPage()
            y = height - 40

    # Финален футър
    draw_footer(c, width)
    c.save()


def draw_footer(c, width):
    """Добавя футър с дата и авторство"""
    c.setFont("Helvetica-Oblique", 8)
    c.setFillGray(0.4)
    footer_text = f"Generated by CyberEdu AI Lab | {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    c.drawCentredString(width / 2, 20, footer_text)
