from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.units import mm
import os
import datetime
import re


def sanitize_filename(name: str) -> str:
    """Премахва неподходящи символи за файлово име"""
    return re.sub(r'[^\w\-_.]', '_', name)


def export_to_pdf(log_text: str, gpt_response: str, filename: str):
    os.makedirs(os.path.dirname(filename), exist_ok=True)

    # ✅ Регистрация на шрифт с кирилица
    font_path = os.path.join("static", "fonts", "DejaVuSans.ttf")
    if not os.path.exists(font_path):
        raise FileNotFoundError(f"❌ Шрифтът не е намерен: {font_path}")

    pdfmetrics.registerFont(TTFont("DejaVu", font_path))

    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    y = height - 40

    # Заглавие
    c.setFont("DejaVu", 14)
    c.drawString(40, y, "CyberEdu AI SOC Report")
    y -= 30

    # Лог секция
    c.setFont("DejaVu", 11)
    c.drawString(40, y, "Лог или входни данни:")
    y -= 20

    c.setFont("DejaVu", 9)
    for line in log_text.splitlines():
        c.drawString(40, y, line)
        y -= 12
        if y < 70:
            draw_footer(c, width)
            c.showPage()
            c.setFont("DejaVu", 9)
            y = height - 40

    # AI анализ
    y -= 10
    c.setFont("DejaVu", 11)
    c.drawString(40, y, "🧠 AI анализ:")
    y -= 20

    c.setFont("DejaVu", 10)
    for line in gpt_response.splitlines():
        c.drawString(40, y, line)
        y -= 13
        if y < 70:
            draw_footer(c, width)
            c.showPage()
            c.setFont("DejaVu", 10)
            y = height - 40

    draw_footer(c, width)
    c.save()


def draw_footer(c, width):
    """Добавя футър с дата и авторство"""
    c.setFont("Helvetica-Oblique", 8)
    c.setFillGray(0.4)
    footer_text = f"Generated by CyberEdu AI Lab | {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    c.drawCentredString(width / 2, 20, footer_text)
